---
apiVersion: rsct.ibm.com/v1alpha1
kind: RSCT
metadata:
  labels:
    app.kubernetes.io/name: rsct
    app.kubernetes.io/instance: rsct
    app.kubernetes.io/part-of: rsct-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: rsct-operator
  name: rsct
spec: {}

